
package views;

import com.sun.glass.events.KeyEvent;

/**
 *
 * @author Hernández Ramírez
 */
public class ViewRFC extends javax.swing.JFrame {

    /**
     * Creates new form ViewRFC
     */
    public ViewRFC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_nombres = new javax.swing.JLabel();
        jl_apellido_pat = new javax.swing.JLabel();
        jl_apellido_mat = new javax.swing.JLabel();
        jtf_nombres = new javax.swing.JTextField();
        jtf_apellido_pat = new javax.swing.JTextField();
        jtf_apellido_mat = new javax.swing.JTextField();
        jl_nota1 = new javax.swing.JLabel();
        jl_anio_nac = new javax.swing.JLabel();
        jl_mes_nac = new javax.swing.JLabel();
        jl_dia_nac = new javax.swing.JLabel();
        jcb_mes_nac = new javax.swing.JComboBox<>();
        jcb_dia_nac = new javax.swing.JComboBox<>();
        jb_obtener = new javax.swing.JButton();
        jb_limpiar = new javax.swing.JButton();
        jl_rfc = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jl_titulo = new javax.swing.JLabel();
        jcb_anio_nac = new javax.swing.JComboBox<>();
        jl_instruccion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro Federal de Contribuyentes");

        jl_nombres.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jl_nombres.setText("Nombre(s):");

        jl_apellido_pat.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jl_apellido_pat.setText("Apellido Paterno:");

        jl_apellido_mat.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jl_apellido_mat.setText("Apellido Materno:");

        jtf_nombres.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jtf_nombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_nombresKeyTyped(evt);
            }
        });

        jtf_apellido_pat.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jtf_apellido_pat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_apellido_patKeyTyped(evt);
            }
        });

        jtf_apellido_mat.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jtf_apellido_mat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_apellido_matKeyTyped(evt);
            }
        });

        jl_nota1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jl_nota1.setText("* En caso de tenerlo.");

        jl_anio_nac.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jl_anio_nac.setText("Año de Nacimiento:");

        jl_mes_nac.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jl_mes_nac.setText("Mes de Nacimiento:");

        jl_dia_nac.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jl_dia_nac.setText("Día de Nacimiento:");

        jcb_mes_nac.setBackground(new java.awt.Color(0, 153, 255));
        jcb_mes_nac.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jcb_mes_nac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        jcb_dia_nac.setBackground(new java.awt.Color(0, 153, 255));
        jcb_dia_nac.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jcb_dia_nac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jb_obtener.setBackground(new java.awt.Color(102, 204, 255));
        jb_obtener.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jb_obtener.setText("Obtener");

        jb_limpiar.setBackground(new java.awt.Color(102, 204, 255));
        jb_limpiar.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jb_limpiar.setText("Limpiar Campos");

        jl_rfc.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jl_rfc.setText("Su RFC es: ");

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jl_titulo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        jl_titulo.setText("OBTENCIÓN DEL RFC");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jl_titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jl_titulo)
                .addGap(28, 28, 28))
        );

        jcb_anio_nac.setBackground(new java.awt.Color(0, 153, 255));
        jcb_anio_nac.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jcb_anio_nac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1900", "1901", "1902", "1903", "1904", "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018" }));

        jl_instruccion.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jl_instruccion.setText("Introduzca los datos utilizando mayúsculas (tecla Bloq Mayus).");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jl_anio_nac)
                                .addGap(18, 18, 18)
                                .addComponent(jcb_anio_nac, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jl_apellido_mat)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtf_apellido_mat))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jl_apellido_pat)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtf_apellido_pat, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jl_nota1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jb_obtener)
                                .addGap(18, 18, 18)
                                .addComponent(jb_limpiar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jl_nombres)
                                .addGap(18, 18, 18)
                                .addComponent(jtf_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jl_dia_nac)
                                    .addGap(18, 18, 18)
                                    .addComponent(jcb_dia_nac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jl_mes_nac)
                                    .addGap(18, 18, 18)
                                    .addComponent(jcb_mes_nac, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jl_instruccion)))
                    .addComponent(jl_rfc))
                .addGap(18, 18, 18))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jl_instruccion)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_nombres))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_apellido_pat)
                    .addComponent(jtf_apellido_pat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_apellido_mat)
                    .addComponent(jtf_apellido_mat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_nota1))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_anio_nac)
                    .addComponent(jcb_anio_nac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_mes_nac)
                    .addComponent(jcb_mes_nac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_dia_nac)
                    .addComponent(jcb_dia_nac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_obtener, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jl_rfc)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_nombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_nombresKeyTyped
        // Text Field para "Nombre(s)".
        
        char letra = evt.getKeyChar(); // Guarda el valor de la tecla presionada en la variable "letra".
        if ((letra < 'A' || letra > 'Z') && letra != KeyEvent.VK_SPACE) { // Comprueba si la tecla presionada es una letra mayúscula o un espacio.
            evt.consume(); // Si cumple los parámetros de restricción, el caracter se "consume".
        }
        
    }//GEN-LAST:event_jtf_nombresKeyTyped

    private void jtf_apellido_patKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_apellido_patKeyTyped
        // Text Field para "Apellido Paterno".
        
        char letra = evt.getKeyChar(); // Guarda el valor de la tecla presionada en la variable "letra".
        if ((letra < 'A' || letra > 'Z') && letra != KeyEvent.VK_SPACE) { // Comprueba si la tecla presionada es una letra mayúscula o un espacio.
            evt.consume(); // Si cumple los parámetros de restricción, el caracter se "consume".
        }
        
    }//GEN-LAST:event_jtf_apellido_patKeyTyped

    private void jtf_apellido_matKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_apellido_matKeyTyped
        // Text Field para "Apellido Materno".
        
        char letra = evt.getKeyChar(); // Guarda el valor de la tecla presionada en la variable "letra".
        if ((letra < 'A' || letra > 'Z') && letra != KeyEvent.VK_SPACE) { // Comprueba si la tecla presionada es una letra mayúscula o un espacio.
            evt.consume(); // Si cumple los parámetros de restricción, el caracter se "consume".
        }
        
    }//GEN-LAST:event_jtf_apellido_matKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewRFC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewRFC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewRFC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewRFC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewRFC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton jb_limpiar;
    public javax.swing.JButton jb_obtener;
    public javax.swing.JComboBox<String> jcb_anio_nac;
    public javax.swing.JComboBox<String> jcb_dia_nac;
    public javax.swing.JComboBox<String> jcb_mes_nac;
    private javax.swing.JLabel jl_anio_nac;
    private javax.swing.JLabel jl_apellido_mat;
    private javax.swing.JLabel jl_apellido_pat;
    private javax.swing.JLabel jl_dia_nac;
    private javax.swing.JLabel jl_instruccion;
    private javax.swing.JLabel jl_mes_nac;
    private javax.swing.JLabel jl_nombres;
    private javax.swing.JLabel jl_nota1;
    public javax.swing.JLabel jl_rfc;
    private javax.swing.JLabel jl_titulo;
    public javax.swing.JTextField jtf_apellido_mat;
    public javax.swing.JTextField jtf_apellido_pat;
    public javax.swing.JTextField jtf_nombres;
    // End of variables declaration//GEN-END:variables
}
